stages:
  prepare:
    cmd: cd notebooks && papermill preprocessing.ipynb ..\ex_notebooks\prep.ipynb
    deps:
      - safety-helmet-1\data.yaml


  train:
    cmd: cd notebooks && papermill training.ipynb ..\ex_notebooks\train.ipynb
    deps:
      - safety-helmet-1\data.yaml
      - params.yaml
      - yolo11m.pt
    outs:
      - runs
